# Generated by Django 4.1.7 on 2023-07-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name_plural': 'DjangoAdmin_panel_mai_Songs'},
        ),
    ]
