# Generated by Django 4.1.7 on 2023-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0007_alter_artists_options'),
        ('Song', '0002_alter_songs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='sung_by_artists',
            field=models.ManyToManyField(related_name='sang_songs', to='Artist.artists'),
        ),
    ]
