# Generated by Django 4.1.7 on 2023-03-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artist', '0005_alter_artists_first_name_alter_artists_stage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('released_by', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='made_album', to='Artist.artists')),
            ],
            options={
                'db_table': 'Albums',
            },
        ),
    ]
