# Generated by Django 4.1.7 on 2023-03-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0007_alter_artists_options'),
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='released_by',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='made_album', to='Artist.artists'),
        ),
    ]
