# Generated by Django 4.1.7 on 2023-03-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artists',
            table='the_artists',
        ),
    ]
