# Generated by Django 4.1.7 on 2023-03-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0002_alter_artists_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='artists',
            name='stage_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
