# Generated by Django 4.1.7 on 2023-03-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0006_alter_artists_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name_plural': 'Django_admin_panel_mai_artists'},
        ),
    ]
